### ISSUE TITLE
what is the commad "dzil"

### ISSUE THREAD

**Issue by cccsnd** [sanger-pathogens/Bio-RNASeq#63]
I had cloned the repo and wanted to install in my PC.But when I run "dzil authordeps | cpanm", it had an error message "bash: dzil: command not found...". How can i fixed this problem? thanks

**Comment by seretol** [comment]
Hi 
You will need to install Dist::Zilla.
Note that a few external dependencies are required.  Feel free to look at the .travis.yml for help.
best,

-oli
